project:
  type: book

book:
  title: "HTML-CSS Zero to Hero"
  author: "Majid Ahmadi"
  date: "7/23/2026"
  
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



