project:
  type: book

lang: fa
language: language/fa.yml

book:
  title: "HTML - CSS  از مبتدی تا حرفه‌ای"
  author: "مجید احمدی"
  date: "7/23/2026"
  
  chapters:
    - index.qmd
    - part: "زبان نشانه‌گذاری فرامتن"
      chapters: 
        - parts\HTML\index.qmd
        - parts\HTML\elements.qmd
    - part: "شیوه‌نامه‌های آبشاری"
      chapters: 
      - parts\CSS\index.qmd
      - parts\CSS\Selectors.qmd
      - parts\CSS\Colors.qmd
    - part: "راهنماها"
      chapters:
      - parts\HowTo\BeforeAfterSlider.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/css/styles.css
    include-after-body:
      - assets/js/main.js
    html-math-method: katex

  # LaTeX does not recognize WebP yet
  # pdf:
  #   documentclass: scrreprt
  # epub:
  #   cover-image: assets/images/cover.webp



