project:
  type: book

lang: fa
language: language/fa.yml

book:
  title: "HTML - CSS  از مبتدی تا حرفه‌ای"
  author: "مجید احمدی"
  date: "7/23/2026"
  
  chapters:
    - index.qmd
    - part: "HTML"
      chapters: 
        - parts\HTML\index.qmd
        - parts\HTML\elements.qmd
    - part: "CSS"
      chapters: 
      - parts\CSS\index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/css/styles.css
    include-after-body:
      - assets/js/main.js
  pdf:
    documentclass: scrreprt
  # epub:
  #   cover-image: assets/images/cover.webp



