# مقدمه
Cascading Style Sheets به معنی  برگه‌های سبک آبشاری.

HTML = اسکلت و ساختار یک وب‌سایت است (مثل استخوان‌بندی بدن). مشخص می‌کند که کجا عنوان باشد، کجا پاراگراف، کجا دکمه و…
CSS = لباس، آرایش و رنگ‌وبوی آن وب‌سایت است. مشخص می‌کند که عنوان چه رنگی باشد، فونت چه شکلی باشد، فاصله‌ها چقدر باشد، صفحه در موبایل چه شکلی دیده شود و…
با CSS می‌توانید:

- رنگ‌ها را تغییر دهید (رنگ متن، رنگ پس‌زمینه، رنگ حاشیه).

- اندازه و نوع قلم (فونت) را تعیین کنید.
فاصله‌ها (فاصله بین خطوط، بین کادرها و حاشیه‌ها) را تنظیم کنید.

- چیدمان المان‌ها را مشخص کنید (مثلاً یک منو را در بالای صفحه، یک عکس را در سمت چپ و یک متن را کنار آن قرار دهید).

- انیمیشن و افکت‌های دیدنی بسازید (مثل بزرگ‌تر شدن دکمه هنگام حرکت ماوس).

- صفحه را واکنش‌گرا (Responsive) کنید؛ یعنی ظاهر سایت در موبایل، تبلت و کامپیوتر فرق کند و به خوبی نمایش داده شود.

 Sass[^1] 
 یک پیش پردازنده [^2]  css هست که به شما امکان می‌دهد کدهای CSS را خیلی حرفه‌ای‌تر، تمیزتر و سریع‌تر بنویسید. مرورگرها مستقیم فایل Sass را نمی‌فهمند، بنابراین شما کد Sass را می‌نویسید و بعد آن را به CSS معمولی تبدیل (کامپایل) می‌کنید و دارای توابع آماده و وراثت نیز هست.
Autoprefixer ابزار دیگری در این حوزه است.بعد از کامپایل Sass، به خروجی CSS نگاه می‌کند و به صورت خودکار تمام پیشوندهای مورد نیاز نسخه های مختلف مرورگرها را به کد اضافه می‌کند.

[^1]:Syntactically Awesome Stylesheets
[^2]:Preprocessor

CSS را می توان به سه روش به سایت اضافه کرد:

- inline (per tag)
- internal (in style tag)
- external (in .css file)

inline به کمک مشخصه style در تگ های HTML:

```html
<a href="#" style="text-decoration: none;">click here</a>
```
اشکال این روش شلوغ شدن کد سایت است که خوانایی آن را کم می کند مزیت آن این است که Specificity[^3] بالاتری دارد.

[^3]:وزن
internal به کمک تگ  style :

```html
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
    <a href="#">click here</a>
</body>
</html>
```

external که روش پر کاربرد است به کمک لینک کردن یک یا چند فایل css به فایل HTML  در تگ head:

```html
<link href="css/style.css" rel="stylesheet"/>
```
و در فایل MyStyles.css  که در پوشه css  قرار دارد کد زیر را درج می کنیم:

```css
a {
    text-decoration: none;
}
```

مهم ترین تفاوت روش های سه گانه تعریف Style وزن و اولویت است.

از شبه کلاس ها و شبه عناصر در روش inline نمی توان استفاده کرد.
